/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Amigo;
import Model.Emprestimo;
import Model.Ferramenta;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinic
 */
public class CadastrarEmprestimo extends javax.swing.JFrame {

    private int idAmigo;
    private int idFerramenta;
    private Amigo objAmigo;
    private Emprestimo objEmprestimo;
    private Ferramenta objFerramenta;

    /**
     * Creates new form CadastrarEmprestimo
     */
    public CadastrarEmprestimo() {
        initComponents();
        objAmigo = new Amigo();
        objEmprestimo = new Emprestimo();
        objFerramenta = new Ferramenta();
        carregaTabelas();
    }

    public void carregaTabelas() {;

        DefaultTableModel tableAmigo = (DefaultTableModel) this.jTable_amigos.getModel();;
        tableAmigo.setNumRows(0);

        ArrayList<Amigo> listaAmigos = new ArrayList<>();
        listaAmigos = objAmigo.getListaAmigos();

        for (Amigo a : listaAmigos) {
            tableAmigo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getTelefone(),
                a.getEmail()
            });
        }

        DefaultTableModel tabelaFerramenta = (DefaultTableModel) this.jTable_ferramentas.getModel();;
        tabelaFerramenta.setNumRows(0);

        ArrayList<Ferramenta> listaFerramentas = new ArrayList<>();
        listaFerramentas = objFerramenta.getListaFerramentas();

        for (Ferramenta f : listaFerramentas) {
            tabelaFerramenta.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getMarca()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel_amigos = new javax.swing.JScrollPane();
        jTable_amigos = new javax.swing.JTable();
        jPanel_ferramentas = new javax.swing.JScrollPane();
        jTable_ferramentas = new javax.swing.JTable();
        jButton_cadastrar = new javax.swing.JButton();
        jButton_cadastrar1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable_amigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Telefone", "Email"
            }
        ));
        jTable_amigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_amigosMouseClicked(evt);
            }
        });
        jPanel_amigos.setViewportView(jTable_amigos);
        if (jTable_amigos.getColumnModel().getColumnCount() > 0) {
            jTable_amigos.getColumnModel().getColumn(0).setMinWidth(0);
            jTable_amigos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jTable_ferramentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Marca"
            }
        ));
        jTable_ferramentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ferramentasMouseClicked(evt);
            }
        });
        jPanel_ferramentas.setViewportView(jTable_ferramentas);
        if (jTable_ferramentas.getColumnModel().getColumnCount() > 0) {
            jTable_ferramentas.getColumnModel().getColumn(0).setMinWidth(0);
            jTable_ferramentas.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jButton_cadastrar.setText("Cadastrar Empréstimo");
        jButton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrarActionPerformed(evt);
            }
        });

        jButton_cadastrar1.setText("Cancelar");
        jButton_cadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_amigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_ferramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_ferramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrarActionPerformed
        // TODO add your handling code here:
        if (idAmigo == 0 || idFerramenta == 0) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, selecione um amigo e uma ferramenta para poder realizar o empréstimo.");
            return;
        }

        try {
            if (objEmprestimo.AmigosHasEmprestimo(idAmigo)) {
                int opcao = JOptionPane.showConfirmDialog(rootPane, "Esse mano aí já tem um empréstimo ativo.\nAinda deseja proseguir com o empréstimo?", "Confirmação", JOptionPane.YES_NO_OPTION);

                if (opcao == JOptionPane.NO_OPTION || opcao == JOptionPane.CANCEL_OPTION || opcao == JOptionPane.CLOSED_OPTION) {
                    return;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }

        Date dataAtual = new Date();

        Calendar calendario = Calendar.getInstance();
        calendario.setTime(dataAtual);
        calendario.add(Calendar.DAY_OF_YEAR, 15);
        Date duasSemanasAFrente = calendario.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd", Locale.US);

        // Format the date to a string
        String data_emprestimo = sdf.format(dataAtual);
        String data_devolucao = sdf.format(duasSemanasAFrente);

        try {

            // envia os dados para o Controlador cadastrar
            if (this.objEmprestimo.InsertEmprestimoDB(idAmigo, idFerramenta, data_emprestimo, data_devolucao)
                    && this.objFerramenta.UpdateFerramentaEmprestimoDB(1, idFerramenta)) {
                JOptionPane.showMessageDialog(rootPane, "Empréstimo efetuado com Sucesso!");
                carregaTabelas();
            }

        } catch (SQLException ex) {
            Logger.getLogger(CadastrarEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_cadastrarActionPerformed

    private void jButton_cadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);        
    }//GEN-LAST:event_jButton_cadastrar1ActionPerformed

    private void jTable_amigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_amigosMouseClicked
        // TODO add your handling code here:

        if (this.jTable_amigos.getSelectedRow() != -1) {

            this.idAmigo = (int) this.jTable_amigos.getValueAt(this.jTable_amigos.getSelectedRow(), 0);

        }
    }//GEN-LAST:event_jTable_amigosMouseClicked

    private void jTable_ferramentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ferramentasMouseClicked
        // TODO add your handling code here:        
        if (this.jTable_ferramentas.getSelectedRow() != -1) {

            idFerramenta = (int) this.jTable_ferramentas.getValueAt(this.jTable_ferramentas.getSelectedRow(), 0);

        }
    }//GEN-LAST:event_jTable_ferramentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cadastrar;
    private javax.swing.JButton jButton_cadastrar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jPanel_amigos;
    private javax.swing.JScrollPane jPanel_ferramentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_amigos;
    private javax.swing.JTable jTable_ferramentas;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
