/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Emprestimo;
import Model.Ferramenta;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEvent;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class GerarRelatorios extends javax.swing.JFrame {

    /**
     * Creates new form GerarRelatorios
     */
    public GerarRelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Gerar Relatório Amigos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gerar Relatório Ferramentas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(162, 162, 162))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Emprestimo objEmprestimo = new Emprestimo();
        ArrayList<Emprestimo> lista = objEmprestimo.getListaEmprestimo();

        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyy_HH.mm.ss");
        String dateTimeString = now.format(formatter);

        Document document = new Document();
        try {
            String filePath = "src/Reports/RelatorioAmigos_" + dateTimeString + ".pdf";
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(filePath));
            writer.setPageEvent(new PDFHeaderFooter("Relatório dos amigos"));
            document.open();

            Paragraph margin = new Paragraph(" ");
            margin.setSpacingAfter(10f);

            document.add(margin);

            // Create a table with 6 columns
            PdfPTable table = new PdfPTable(6);

            // Set table properties
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);

            // Add table headers
            table.addCell("ID");
            table.addCell("ID Amigo");
            table.addCell("Nome Amigo");
            table.addCell("Nome Ferramenta");
            table.addCell("Data Empréstimo");
            table.addCell("Data Devolução");

            // Add table rows from the list
            for (Emprestimo emprestimo : lista) {
                table.addCell(String.valueOf(emprestimo.getId()));
                table.addCell(String.valueOf(emprestimo.getAmigo_id()));
                table.addCell(emprestimo.getNomeAmigo());
                table.addCell(emprestimo.getNomeFerramenta());
                table.addCell(emprestimo.getData_emprestimo());
                table.addCell(emprestimo.getData_devolucao());
            }

            // Add the table to the document
            document.add(table);

            document.close();
            JOptionPane.showMessageDialog(rootPane, "PDF gerado com sucesso!");
        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GerarRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Ferramenta objFerramenta = new Ferramenta();

        ArrayList<Ferramenta> lista = objFerramenta.getListaPDF();

        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyy_HH.mm.ss");
        String dateTimeString = now.format(formatter);

        Document document = new Document();
        try {
            String filePath = "src/Reports/RelatorioFerramentas_" + dateTimeString + ".pdf";
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(filePath));
            writer.setPageEvent(new PDFHeaderFooter("Relatório de Ferramentas"));
            document.open();

            Paragraph margin = new Paragraph(" ");
            margin.setSpacingAfter(15f);

            document.add(margin);

            // Create a table with 6 columns
            PdfPTable table = new PdfPTable(5);

            // Set table properties
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);

            Font headerFont = FontFactory.getFont(FontFactory.COURIER_BOLD, 12);
            PdfPCell cell = new PdfPCell(new Phrase("Nome", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setMinimumHeight(28f);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Marca", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setMinimumHeight(28f);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Custo", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setMinimumHeight(28f);
            table.addCell(cell);
            
            cell = new PdfPCell(new Phrase("Custo Total", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setMinimumHeight(28f);
            table.addCell(cell);
            
            cell = new PdfPCell(new Phrase("Quantidade", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setMinimumHeight(28f);
            table.addCell(cell);

            float totalCost = 0;

            // Add table rows from the list
            for (Ferramenta ferramenta : lista) {
                table.addCell(String.valueOf(ferramenta.getNome()));
                table.addCell(String.valueOf(ferramenta.getMarca()));
                table.addCell(String.valueOf(ferramenta.getCusto()));
                table.addCell(String.valueOf(ferramenta.getCustoTotal()));
                table.addCell(String.valueOf(ferramenta.getQntEstoque()));
                totalCost += ferramenta.getCustoTotal();
            }

            // Add the table to the document
            document.add(table);

            document.add(margin);

            Paragraph paragraph = new Paragraph();
            paragraph.setAlignment(Element.ALIGN_RIGHT);
            paragraph.add(new Chunk("Total Custo: "));
            paragraph.add(new Chunk(String.valueOf(totalCost)));
            document.add(paragraph);

            document.close();
            JOptionPane.showMessageDialog(rootPane, "PDF gerado com sucesso!");
        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GerarRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerarRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
